### ISSUE TITLE
Convert to WebP on the fly?

### ISSUE THREAD

**Issue by nucliweb** [cyrilwanner/react-optimized-image#1]
Hi,

first of all, I think that is an interesting project.

I have a question about **Convert to WebP on the fly**, I not understand the objective.
If the original image is an JPEG or PNG format, and the component generate the WebP on the fly, the user are downloading the "unoptimized" image, right?

**Comment by nucliweb** [comment]
Wait this component is to use with a [Next.js](https://nextjs.org/) project.

I have not said anything 😅


![](https://media.giphy.com/media/1zSz5MVw4zKg0/giphy-downsized-large.gif)

**Comment by cyrilwanner** [comment]
It can also be used outside of a next.js project. But you are right, on the fly is maybe the wrong naming. The image gets converted to WebP during a webpack build, so the browsers only download the webp version in the end if they support it. I'll change the naming ;)
