### ISSUE TITLE
Size array ordering

### ISSUE THREAD

**Issue by justsee** [cyrilwanner/react-optimized-image#3]
Due to the way [the sizes array is computed](https://github.com/cyrilwanner/react-optimized-image/blob/d28749be91b8db6f514fc6d687b6c741e0ff1072/src/components/Img.tsx#L52) any configuration that includes out-of-order numbers will be converted to an ordered array.

So `sizes: [300, 500, 150]` appears to resolve to `[150, 300, 500]` when generating the `picture` output, and in combination with specifying breakpoints will generate different `srcset` combinations of `src` image and media queries than expected.

This was while experimenting with a responsive grid of images: a situation where as the viewport widens smaller images are required.

(This might be a use case better served by using `sizes` of `source` in combination with width descriptors in `srcset` but I think only pixel density descriptors and media queries are available here).

**Comment by cyrilwanner** [comment]
Hi @justsee 
Thank you very much for the bug report. I just published a new version in which this should be fixed (for both `react-optimized-image` and `next-optimized-images` in case you are also using that). Can you test this new version and check if everything is correct? Thanks!

**Comment by justsee** [comment]
Great - thanks for jumping on that, and can confirm that resolves this issue (and yes I was using this via `next-optimized-images`).
